include: "rules/common.smk"


if config.get("load_fair_genome_indexer", True):

    include: "rules/fair_genome_indexer.smk"


if config.get("load_fair_fastqc_multiqc", True):

    include: "rules/fair_fastqc_multiqc.smk"


if config.get("load_fair_bowtie2_mapping", True):

    include: "rules/fair_bowtie2_mapping.smk"


include: "rules/multiqc.smk"
include: "rules/picard.smk"
include: "rules/preseq.smk"
include: "rules/regtools.smk"
include: "rules/rnaseqc.smk"
include: "rules/sambamba.smk"
include: "rules/star.smk"

ruleorder: fair_star_mapping_picard_add_or_replace_groups > fair_bowtie2_mapping_sambamba_markdup


rule fair_star_mapping_target:
    input:
        unpack(get_fair_star_mapping_target),
    output:
        touch("tmp/targets/fair_star_mapping_target.flag"),
    localrule: True
    threads: 1
    resources:
        mem_mb=128,
        runtime=2,
        tmpdir="tmp",
    log:
        "logs/fair_star_mapping_target.log",
    benchmark:
        "benchmark/fair_star_mapping_target.tsv"
