samples: config/samples.csv

#params:

# Optional path to a `genome.csv` file
genomes: config/genomes.csv

# Internal use only, not described in documentation.
# deactivate import of fair_genome_indexer pipeline.
# Requires the file `genome.csv` to be filled.
# load_fair_genome_indexer: true
# deactivate import of fair_bowtie2_mapping pipeline.
# This is used for QC and compression, mapping is done by STAR in any case.
# load_fair_bowtie2_mapping: true
